version: '3.3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    restart: always
        
  rabbitmq: 
    image: "rabbitmq:3-management-alpine"
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
      
  downloadserivce:
    image: "vidloadworkerdownloadservice:latest"
    volumes:
      - type: volume
        source: mediastorage
        target: /opt/mediastorage
    depends_on:
      - redis
      - rabbitmq
    restart: always
    deploy:
      mode: replicated
      replicas: 5
    
  metadatacollector:
    image: "vidloadworkermetadatacollector:latest"
    depends_on:
      - redis
      - rabbitmq
    restart: always
    deploy:
      mode: replicated
      replicas: 5
  
volumes:
  mediastorage:
